version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
      #   networks:
      #- detroitpirates
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "81:80/tcp"
    environment:
      TZ: 'America/Detroit'
      # WEBPASSWORD: 'set a secure password here or it will be random'
      VIRTUAL_HOST: piehole.local
      piehole_domain: detroitpirates-lan
      webtheme: default dark
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    networks:
      - detroitpirates-lan
    labels:
      - "traefik.http.routers.pihole.rule=Host(`pihole.domain.tld`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=letsencrypt"
      - "traefik.http.routers.pihole.tls.domains[0].main=pihole.domain.tld"
      - "traefik.http.routers.pihole.tls.domains[0].sans=pihole.domain.tld"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    cap_add:
      - NET_ADMIN
    restart: always


networks:
  detroitpirates-lan:
    external: true
